version: "3.3"
    
services:
  wordpress:
    image: wordpress:latest
    mem_limit: 2048M
    mem_reservation: 256M
    cpus: 0.5
    volumes: ["./html:/var/www/html"]
    ports:
      - "${PORT:-8000}:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}