name: DEV-DEPLOY


on:
  push:
    branches: [ dev ]

    
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
        with:
          path: dev
          
      - name: Create .env file
        run: |
          echo 'PORT=${{ secrets.DEV_PORT }}' > .env
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> .env
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
          echo 'DB_PASS=${{ secrets.DB_PASS }}' >> .env
          echo 'DB_NAME=${{ secrets.DB_NAME_DEV }}' >> .env
      
      - name: Run DEV container
        run: |
          docker-compose -f dev-docker-compose.yml --compatibility up -d
